version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: lottery
      POSTGRES_USER: fah
      POSTGRES_PASSWORD: fah240342
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

