services:
  db:
    image: postgres:16
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: lottery
      POSTGRES_USER: lottery_service
      POSTGRES_PASSWORD: lottery_p@ssw0d
    ports:
      - "5432:5432"

volumes:
  db_data:
