name: Automate Workflow
on:
  push:
    branches: [ main ]

jobs:
  unit-test:
    name: Run Unit Test
    runs-on: ubuntu-latest
    steps:
      -   name: Checkout Code
          uses: actions/checkout@v3
      -   name: Setup Java17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'zulu'
      -   name: Run Unit Tests
          run: ./gradlew test