version: '3.8'

networks:
  lottery-service-network:

services:
  postgres-db:
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_DB: lottery-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - lottery-service-network

  app:
    build: .
    restart: on-failure
    depends_on:
      - postgres-db
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres-db:5432/lottery-db
      - DATABASE_USERNAME=user
      - DATABASE_PASSWORD=password
    ports:
      - "8888:8888"
    networks:
      - lottery-service-network

volumes:
  postgres-data: