version: '3'
services:
  app:
    build: .
    ports:
      - "8888:8888"
    environment:
      - DATABASE_URL=jdbc:postgresql://localhost:5432/lottery
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lottery