#file: noinspection YAMLSchemaValidation
version: '3.8'

networks:
  integration-test-example:

services:
  it_test:
    image: amazoncorretto:17.0.9-alpine3.18
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db
    networks:
      - integration-test-example
    command: ["./gradlew","clean","integrationTest"]
  db:
    image: postgres:16.0
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lottery
    restart: on-failure
  
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - integration-test-example