version: '3'
networks:
  integration-test:
services:
  it_test:
    image: amazoncorretto:17.0.9-alpine3.18
    volumes:
      - $PWD:/app
    working_dir: /app
    depends_on:
      - postgres
    networks:
      - integration-test
    command: ["./gradlew","clean","test"]
  postgres:
    image: postgres:latest
    environment:
      url: ${DATABASE_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
    volumes:
      # - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - integration-test
    ports:
      - "5432:5432"

volumes:
  pgdata:
