version: '3.8'

networks:
  lottery-service-network:

services:
  postgres-db:
    container_name: lottery-postgres-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: lottery-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - lottery-service-network

  app:
    container_name: lottery-app
    build:
      context: .
      dockerfile: Dockerfile
    image: amazoncorretto:17.0.9-alpine3.18
    restart: always
    volumes:
      - $PWD:/app
    working_dir: /app
    depends_on:
      - postgres-db
    environment:
      - DATABASE_URL=${DATABASE_PWD}
      - DATABASE_USERNAME=user
      - DATABASE_PWD=password
    ports:
      - "8888:8888"
    networks:
      - lottery-service-network
#    command: [ "./gradlew"]
