#server.port=8888
#spring.datasource.url=jdbc:postgresql://localhost:5432/<YOUR_DATABASE_NAME>
#spring.datasource.username=<YOUR_USERNAME>
#spring.datasource.password=<YOUR_PASSWORD>
#spring.jpa.hibernate.ddl-auto=<create | create-drop | update | validate | none>
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8888

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lotteryDB
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

